CREATE TABLE TB_USER (
	userId BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL,
    fullname VARCHAR(256) NOT NULL,
    email VARCHAR(128) NOT NULL,
    walletId BIGINT(10) UNSIGNED,
    PRIMARY KEY(userId)
);

CREATE TABLE TB_WALLET (
	walletId BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(256) NOT NULL,
    balance DOUBLE DEFAULT '0',
    userId BIGINT(10) UNSIGNED,
    PRIMARY KEY(walletId),
    CONSTRAINT FK_WALLET_USER FOREIGN KEY (userId) REFERENCES TB_USER(userId)
);

CREATE TABLE TB_ENTRY (
	entryId BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    description VARCHAR(256) NOT NULL,
    entryType VARCHAR(16) NOT NULL,
    origin VARCHAR(16) NOT NULL,
    entryDate DATE,
    value DOUBLE NOT NULL DEFAULT '0',
    walletId BIGINT(10) UNSIGNED,
    PRIMARY KEY(entryId),
    CONSTRAINT FK_ENTRY_WALLET FOREIGN KEY (walletId) REFERENCES TB_WALLET(walletId)
);

ALTER TABLE TB_USER ADD CONSTRAINT FK_USER_WALLET FOREIGN KEY (walletId) REFERENCES TB_WALLET(walletId);